# Generated by Django 5.2.5 on 2025-09-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_contenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenir',
            name='qte',
            field=models.IntegerField(default=0),
        ),
    ]
