# Generated by Django 5.2.5 on 2025-09-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0004_contenir_qte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idStatus', models.AutoField(primary_key=True, serialize=False)),
                ('libelleStatus', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='dateFabrication',
            field=models.DateField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='contenir',
            name='produits',
        ),
        migrations.RemoveField(
            model_name='contenir',
            name='rayons',
        ),
        migrations.AddField(
            model_name='contenir',
            name='produits',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='monApp.produit'),
        ),
        migrations.AddField(
            model_name='contenir',
            name='rayons',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='monApp.rayon'),
        ),
    ]
