# Generated by Django 5.2.5 on 2025-09-11 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_produit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='dateFabrication',
            field=models.DateField(default=datetime.date(2025, 9, 11)),
        ),
    ]
