# Generated by Django 5.2.5 on 2025-10-09 06:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0007_alter_produit_datefabrication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenir',
            name='produits',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contenir_produit', to='monApp.produit'),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='rayons',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contenir_rayon', to='monApp.rayon'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='dateFabrication',
            field=models.DateField(default=datetime.date(2025, 10, 9)),
        ),
        migrations.AlterField(
            model_name='produit',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit', to='monApp.statut'),
        ),
        migrations.AlterUniqueTogether(
            name='contenir',
            unique_together={('rayons', 'produits')},
        ),
    ]
